In [32]:
import numpy as np
import pandas as pd
from matplotlib.pyplot import subplots
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor as VIF
from statsmodels.stats.anova import anova_lm

In [33]:
from ISLP import load_data
from ISLP.models import (ModelSpec as MS, summarize, poly)

In [34]:
# lists everything we can interact with. dir() with no arguments
# will list everything that we have imported or defined in the current notebook. 
dir()

['Boston',
 'In',
 'MS',
 'Out',
 'VIF',
 'X',
 '_',
 '_10',
 '_11',
 '_13',
 '_16',
 '_17',
 '_18',
 '_20',
 '_23',
 '_24',
 '_25',
 '_26',
 '_27',
 '_28',
 '_29',
 '_30',
 '_31',
 '_4',
 '_5',
 '_7',
 '_9',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '__vsc_ipynb_file__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i11',
 '_i12',
 '_i13',
 '_i14',
 '_i15',
 '_i16',
 '_i17',
 '_i18',
 '_i19',
 '_i2',
 '_i20',
 '_i21',
 '_i22',
 '_i23',
 '_i24',
 '_i25',
 '_i26',
 '_i27',
 '_i28',
 '_i29',
 '_i3',
 '_i30',
 '_i31',
 '_i32',
 '_i33',
 '_i34',
 '_i4',
 '_i5',
 '_i6',
 '_i7',
 '_i8',
 '_i9',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'anova_lm',
 'design',
 'exit',
 'get_ipython',
 'load_data',
 'model',
 'newX',
 'new_df',
 'new_predictions',
 'np',
 'open',
 'pd',
 'poly',
 'quit',
 'results',
 'sm',
 'subplots',
 'summarize',
 'y']

In [35]:
# importing the required dataset using the load_data method provided in the ISLP package. 
Boston=load_data("Boston")
Boston.columns

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'lstat', 'medv'],
      dtype='object')

In [36]:
Boston

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,7.88,11.9

In [37]:
# A Regression model has 4 main steps regardless of the dataset being used.

Step 1: Build the predictor matrix.

In [38]:
# Boston.shape[0] counts the number of rows in the dataset. 
# np.ones is generating a list of 1's for each row in the dataset. For linear regression, we need an intercept constant(B0) that is part of the equation. To make sure the matrix multiplication is a success we need a variable to multiply B0 with. 
# By multiplying B0 with the 1's representing each row, it returns the exact same value. 

# lstat here grabs the column lower_status that represents proportion of residents in the neighbourhood classified as LOW INCOME. 
X=pd.DataFrame({ # represents a key value pair. 
    'intercept':np.ones(Boston.shape[0]),
    'lstat': Boston['lstat']})
X[:4]

   intercept  lstat
0        1.0   4.98
1        1.0   9.14
2        1.0   4.03
3        1.0   2.94

Step 2: Instantiate the target

In [39]:
y=Boston['medv']

Step 3: Instantiate and fit the model

In [40]:
# sm.ols is specific to linear regression models, where OLS stands for Ordinary least squares which is the foundations for calculating the equation of a straigh line by minimizing the squared differences between data points and the line. 
# sm.ols defines model, does not fit it. 
model=sm.OLS(y, X)

# model.fit does the actual fitting. 
results=model.fit()

Step 4: Interpret the model

In [41]:
summarize(results)

              coef  std err       t  P>|t|
intercept  34.5538    0.563  61.415    0.0
lstat      -0.9500    0.039 -24.528    0.0

In [42]:
# fit method analyses the dataset and calculates statistical metrics like means, standard deviations etc. 
# transform modifies the dataset. It uses the values that were calculated during the fit step and transforms any additional data and the orignal dataset after new fit rules have been calculated. 
design=MS(['lstat'])
X=design.fit_transform(Boston)
X[:4]

   intercept  lstat
0        1.0   4.98
1        1.0   9.14
2        1.0   4.03
3        1.0   2.94

In [43]:
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   medv   R-squared:                       0.544
Model:                            OLS   Adj. R-squared:                  0.543
Method:                 Least Squares   F-statistic:                     601.6
Date:                Sat, 04 Jul 2026   Prob (F-statistic):           5.08e-88
Time:                        22:57:19   Log-Likelihood:                -1641.5
No. Observations:                 506   AIC:                             3287.
Df Residuals:                     504   BIC:                             3295.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
intercept     34.5538      0.563     61.415      0.000      33.448      35.659
lstat         -0.9500      0.039    -24.528      0.000      -1.026      -0.874
==============================================================================
Omnibus:                      137.043   Durbin-Watson:                   0.892
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              291.373
Skew:                           1.453   Prob(JB):                     5.36e-64
Kurtosis:                       5.319   Cond. No.                         29.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [44]:
results.params

intercept    34.553841
lstat        -0.950049
dtype: float64

In [45]:
# simulation of what would happen if you introduce new values to your dataset which were not included when the model was being trained. 
new_df=pd.DataFrame({'lstat':[5, 10, 15]})

# the model has already learnt the rules and calculated statistical metrics like std dev on the entire dataset, therefore we only call transform and not fit and transform
newX=design.transform(new_df)
newX

   intercept  lstat
0        1.0      5
1        1.0     10
2        1.0     15

In [46]:
new_predictions=results.get_prediction(newX);
new_predictions.predicted_mean

array([29.80359411, 25.05334734, 20.30310057])

In [47]:
# confidence interval= estimates the uncertainity around the mean. 
new_predictions.conf_int(alpha=0.5)

array([[29.53006154, 30.07712669],
       [24.85435487, 25.25233981],
       [20.10675447, 20.49944667]])

In [48]:
# prediction inderval= estimates the uncertainity around a single data point in the future. 
new_predictions.conf_int(obs=True, alpha=0.5)

array([[25.59919254, 34.00799568],
       [20.85313657, 29.25355811],
       [16.10301435, 24.5031868 ]])